/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.aptech.LoanProcessingSystem.view;

import java.awt.BorderLayout;
import java.awt.Color;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PiePlot3D;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.renderer.category.BarRenderer;
import org.jfree.chart.renderer.category.BarRenderer3D;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.general.DefaultPieDataset;
import org.jfree.data.jdbc.JDBCCategoryDataset;

import com.aptech.LoanProcessingSystem.database.ConnectDB;
import com.aptech.LoanProcessingSystem.service.ShareData;

import java.awt.Toolkit;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.ImageIcon;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.awt.event.ActionEvent;

/**
 *
 * @author triquang
 */
public class Statistic extends javax.swing.JFrame {

	// Variables declaration - do not modify
	private javax.swing.JButton btn3DPie;
	private javax.swing.JButton btnBarChart;
	private javax.swing.JButton btnLineChart;
	private javax.swing.JPanel pnChart;

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(Statistic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(Statistic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(Statistic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(Statistic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				try {
					if (ShareData.accountLogin == null) {
						Login login = new Login();
						login.setVisible(true);
					} else {
						new Statistic().setVisible(true);
					}
				} catch (Exception e) {
					e.printStackTrace();
				}
			}
		});
	}

	/**
	 * Creates new form MainFrm
	 */
	public Statistic() {
		setDefaultCloseOperation(JDialog.DO_NOTHING_ON_CLOSE);
		addWindowListener(new java.awt.event.WindowAdapter() {
			@Override
			public void windowClosing(java.awt.event.WindowEvent windowEvent) {
				cancelAction();
			}
		});
		setIconImage(Toolkit.getDefaultToolkit()
				.getImage(Statistic.class.getResource("/com/aptech/LoanProcessingSystem/images/bank (4).png")));
		setTitle("Statistic");
		getContentPane().setBackground(new Color(169, 169, 169));
		initComponents();
		this.setLocationRelativeTo(null);
		setExtendedState(getExtendedState() | JFrame.MAXIMIZED_BOTH);
		pnChart.setLayout(new java.awt.BorderLayout());
	}

	private DefaultCategoryDataset createDataset() {
		// same dataset for line chart and bar chart
		DefaultCategoryDataset dataset = new DefaultCategoryDataset();
		dataset.addValue(15, "Loan", "2017");
		dataset.addValue(30, "Loan", "2018");
		dataset.addValue(60, "Loan", "2019");
		dataset.addValue(120, "Loan", "2020");
		dataset.addValue(240, "Loan", "2021");
		dataset.addValue(300, "Loan", "2022");

		return dataset;
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		pnChart = new javax.swing.JPanel();
		btnLineChart = new javax.swing.JButton();
		btnLineChart.setBackground(new Color(255, 140, 0));
		btnBarChart = new javax.swing.JButton();
		btnBarChart.setBackground(new Color(255, 140, 0));
		btn3DPie = new javax.swing.JButton();
		btn3DPie.setBackground(new Color(255, 140, 0));
		pnChart.setBorder(javax.swing.BorderFactory.createEtchedBorder());
		javax.swing.GroupLayout pnChartLayout = new javax.swing.GroupLayout(pnChart);
		pnChart.setLayout(pnChartLayout);
		pnChartLayout.setHorizontalGroup(pnChartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 0, Short.MAX_VALUE));
		pnChartLayout.setVerticalGroup(pnChartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 333, Short.MAX_VALUE));

		btnLineChart.setText("Line Chart");
		btnLineChart.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnLineChartActionPerformed(evt);
			}
		});

		btnBarChart.setText("Bar Chart");
		btnBarChart.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnBarChartActionPerformed(evt);
			}
		});

		btn3DPie.setText("3D Pie Chart");
		btn3DPie.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btn3DPieActionPerformed(evt);
			}
		});

		JButton btnNewButton = new JButton("Close");
		btnNewButton.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				cancelAction();
			}
		});
		btnNewButton.setBackground(new Color(169, 169, 169));
		btnNewButton.setIcon(
				new ImageIcon(Statistic.class.getResource("/com/aptech/LoanProcessingSystem/images/close (2).png")));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		layout.setHorizontalGroup(layout.createParallelGroup(Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addContainerGap()
						.addGroup(layout.createParallelGroup(Alignment.TRAILING)
								.addComponent(pnChart, GroupLayout.DEFAULT_SIZE, 511, Short.MAX_VALUE)
								.addGroup(layout.createSequentialGroup().addComponent(btnNewButton)
										.addPreferredGap(ComponentPlacement.RELATED, 137, Short.MAX_VALUE)
										.addComponent(btn3DPie).addGap(18).addComponent(btnBarChart)
										.addPreferredGap(ComponentPlacement.UNRELATED).addComponent(btnLineChart)))
						.addContainerGap()));
		layout.setVerticalGroup(layout.createParallelGroup(Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addContainerGap()
						.addComponent(pnChart, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addGap(18)
						.addGroup(layout.createParallelGroup(Alignment.BASELINE).addComponent(btnLineChart)
								.addComponent(btnBarChart).addComponent(btn3DPie).addComponent(btnNewButton))
						.addContainerGap()));
		getContentPane().setLayout(layout);

		pack();
	}// </editor-fold>

	private void cancelAction() {
		this.dispose();
	}

	private void btnLineChartActionPerformed(java.awt.event.ActionEvent evt) {
		// create line chart
		JFreeChart lineChart = ChartFactory.createLineChart("Number of Loan vs years", "Years", "Loan of Loan",
				createDataset(), PlotOrientation.VERTICAL, true, true, false);
		// set color
		CategoryPlot plot = (CategoryPlot) lineChart.getPlot();
		plot.getRenderer().setSeriesPaint(0, Color.BLUE);
		// create chart panel the add it to swing panel in jframe
		ChartPanel chartPanel = new ChartPanel(lineChart);
		pnChart.removeAll(); // clear panel before add new chart
		pnChart.add(chartPanel, BorderLayout.CENTER);
		pnChart.validate(); // refresh panel to display new chart
	}

	private void btnBarChartActionPerformed(java.awt.event.ActionEvent evt) {
		// create bar chart
		JFreeChart barChart = ChartFactory.createBarChart("Number of Loan vs years", "Years", "Number of Loan",
				createDataset(), PlotOrientation.VERTICAL, true, true, false);
		// set color
		CategoryPlot plot = (CategoryPlot) barChart.getPlot();
		plot.getRenderer().setSeriesPaint(0, Color.BLUE);
		// create chart panel the add it to swing panel in jframe
		ChartPanel chartPanel = new ChartPanel(barChart);
		pnChart.removeAll(); // clear panel before add new chart
		pnChart.add(chartPanel, BorderLayout.CENTER);
		pnChart.validate(); // refresh panel to display new chart
	}

	private void btn3DPieActionPerformed(java.awt.event.ActionEvent evt) {

		// create dataset for pie chart
		DefaultPieDataset dataset = new DefaultPieDataset();
		dataset.setValue("Home Loan", new Double(20));
		dataset.setValue("Vehicle Loan", new Double(20));
		dataset.setValue("Personal Loan", new Double(40));
		dataset.setValue("Educational", new Double(10));
		// create pir chart
		JFreeChart chart = ChartFactory.createPieChart3D("Loan Type", // chart title
				dataset, // data
				true, // include legend
				true, false);
		// set chart properties
		final PiePlot3D plot = (PiePlot3D) chart.getPlot();
		plot.setStartAngle(270);
		plot.setForegroundAlpha(0.60f);
		plot.setInteriorGap(0.02);
		// create chart panel the add it to swing panel in jframe
		ChartPanel chartPanel = new ChartPanel(chart);
		pnChart.removeAll(); // clear panel before add new chart
		pnChart.add(chartPanel, BorderLayout.CENTER);
		pnChart.validate(); // refresh panel to display new chart
	}

}
